#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

echo "HERE: $(pwd)"

# find the installers and run them iteratively
#find . -name install.sh | while read installer
for installer in $(find . -name install.sh)
do
    echo "Running: ${installer}..."
    sh -c "${installer}"
done
